### ISSUE TITLE
"Don't use this"

### ISSUE THREAD

**Issue by morewry** [thejameskyle/bootcamp#107]
I prefer BDD-style testing like bootcamp to the more classic assert style used by true, so had been leaning toward using bootcamp.  Just noticed the README now says as its main title "Don't use this", but couldn't find any further information.

Does that mean people shouldn't begin using bootcamp?  And does anyone have additional information on why, the future, or alternatives?

**Comment by thejameskyle** [comment]
I originally wrote this as an experiment, I have no desire to maintain it anymore though. There's also only a handful of developers who should be writing tests for their sass code anyways.

If someone wants to fork the project and maintain it, then sure it would be fine to use that. But please don't use this otherwise.

**Comment by morewry** [comment]
Cool, thanks for the info!
